name: Get Feed

on:
  schedule:
    - cron: '30 13 * * *' # beijing 0230 am temp
  workflow_dispatch:

jobs:
  get-feed:
    name: Run rust
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_SOURCE_DATABASE_ID: ${{ secrets.NOTION_SOURCE_DATABASE_ID }}
      NOTION_FEED_DATABASE_ID: ${{ secrets.NOTION_FEED_DATABASE_ID }}
    steps:
      - name: Update Notion Feed
        run: |
          curl -L -o notion-feed https://github.com/abereghici/notion-feed.rs/raw/build/build/notion-feed 
          chmod +x ./notion-feed 
          ./notion-feed
